export enum ShotType {
  Heave = "heave",
  Jumper = "jumper",
  Post = "post",
  Floater = "floater",
  Layup = "layup",
}

export enum ComplexShotType {
  Heave = "heave",
  CatchAndShoot = "catchAndShoot",
  CatchAndShootRelocating = "catchAndShootRelocating",
  CatchAndShootOnMoveLeft = "catchAndShootOnMoveLeft",
  CatchAndShootOnMoveRight = "catchAndShootOnMoveRight",
  PullupJumper = "pullupJumper",
  Stepback = "stepback",
  ShakeAndRaise = "shakeAndRaise",
  OverScreen = "overScreen",
  DrivingFloater = "drivingFloater",
  CutFloater = "cutFloater",
  PostLeft = "postLeft",
  PostRight = "postRight",
  DrivingLayup = "drivingLayup",
  CutLayup = "cutLayup",
  StandstillLayup = "standstillLayup",
  Lob = "lob",
  Tip = "tip",
}

export enum ContestLevel {
  Uncontested = "uncontested",
  LightlyContested = "lightly_contested",
  HeavilyContested = "heavily_contested",
}

export type Shot = {
  /** Unique identifier generated by database */
  id: number;

  /** Unique ID of shooter */
  shooter_id: string;

  /** Name of shooter */
  shooter_name: string;

  /** Year shot was taken */
  year: number;

  /** Month shot was taken */
  month: number;

  /** Day shot was taken */
  day: number;

  /** Regulation periods 1-4, overtime periods 5 and up */
  period: number;

  /** Seconds remaining in period when shot was released */
  start_game_clock: string;

  /** Seconds remaining in period when shot reached the rim,respectively */
  end_game_clock: string;

  /** Seconds remaining on shot clock when shot was released */
  shot_clock: number;

  /** x coordinate of shooter when shot was released */
  x: number;

  /** y coordinate of shooter when shot was released */
  y: number;

  /** True if the shot was made, false if missed */
  outcome: boolean;

  /** x coordinate of the passer when the ball was passed to the shooter */
  passer_x: number | null;

  /** y coordinate of the passer when the ball was passed to the shooter */
  passer_y: number | null;

  /** True if the shot was marked with an assist in the play-by-play */
  assisted: boolean;

  /** True if the shooter took <= 1 dribbles and held the ball for less than 2.5 seconds */
  ast_opp: boolean;

  /** True if shot was blocked, false otherwise */
  blocked: boolean;

  /** True if the shooter was fouled, false otherwise */
  fouled: boolean;

  /** Shot type used to score */
  shot_type: ShotType;

  /** Complex shot type used to score */
  complex_shot_type: ComplexShotType;

  /** True if any defenders contested the shot, false otherwise */
  contested: boolean;

  /** Contest level of the shot */
  contest_level: ContestLevel;

  /** True if 0 dribbles before shooting, false if shooter dribbled */
  catch_and_shoot: boolean;

  /** The number of dribbles the shooter took before shooting */
  dribbles_before: number;
};
